def ogrenme_asamasi():
    print("Şuan da öğrenme aşamasındasınız.")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Evde musluk tamir etmek.")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin bir tamir videosu izleyip musluğun nasıl tamir edileceğine bakarsın ve daha sonra musluk bir daha bozulduğunda tekrar tamir edebilirsin.")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama bir usta çağırırsan her seferinde ustaya para ödemek zorunda kalırsın ve ustayı çağırmadan musluğu tamir edemezsin ve böylece öğrenme süreci daha uzun sürer.")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Yazılım kodlamak.")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin youtubedan veya internet üzerinden derslerden yazılım öğrenip daha sonra bir yazılım projesi yapabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama istediğin bir şeyi her seferinde yapay zekaya yaptırırsan hiçbir şey öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Video editlemek.")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin bir video editleme programı öğrenip daha sonra kendi videolarını editleyebilirsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Çarpım tablosunu öğrenmek.")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Çarpım tablosuna çalışıp ezberleyerek öğrenmek.")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde çarpım tablosunu ezberlemek yerine bir hesap makinesi kullanırsan hiçbir şey öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Yemek yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin yemek tariflerini öğrenip daha sonra kendi yemeklerini yapabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde yemek yapmak yerine bir restorana gidip yemek yersen hiçbir şey öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Resim yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin resim yapmayı öğrenip daha sonra kendi resimlerini yapabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde resim yapmak yerine sürekli dışardan resmi alırsan hiçbir şey öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Müzik yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin müzik aletlerini öğrenip daha sonra kendi müzik parçalarını yapabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde müzik yapmak yerine sürekli dışardan müzik dinlersen hiçbir şey öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Yön bulma")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin yön bulmayı öğrenip daha sonra kendi başına yön bulabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde yön bulmak yerine sürekli navigasyon kullanırsan telefonun olmadığı zaman kaybolabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Spor Yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin spor yapmayı öğrenip kas hafızanı eğitip güçlenebilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama eşyalarını her seferinde başkasına taşıttırırsan güçlenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Fotoğraf çekmek")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin fotoğraf çekmeyi,doğru ışık noktalarını bilmeyi öğrenip daha sonra kendi fotoğraflarını çekebilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde başkasına fotoğraflarını çektirirsen hiçbir şey öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Araba tamir etmek")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin araba tamir etmeyi öğrenip daha sonra kendi arabalarını tamir edebilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde arabayı tamir etmek yerine bir usta çağırırsan hiçbir şey öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Oyun oynamak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin oyun mekaniklerini öğrenip yüksek ranklara çıkabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama hesap kasmaya uğraşmak yerine hesabını boost ettirirsen oyunda gelişemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Alışveriş yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendi bütçene ve kumaş kalitesine bakıp alışveriş yapabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama yapay zekaya bana kombin yap dersen bütçene uygun olanları seçmeyebilir ve istediğimiz modelleri göstermeyebilir")
    input("Devam etmek için Enter'a bas")
    print("Örnek:grafik tasarım yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin grafik tasarım yapmayı öğrenip daha sonra kendi tasarımlarını yapabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde grafik tasarım yapmak yerine sürekli yapay zekaya başvurursan hem istediğin gibi olmayabilir hem de hiçbir şey öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Video oyunları yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin oyun yapmayı öğrenip daha sonra kendi oyunlarını yapabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde oyun yapmak yerine sadece dışarıdan oyun alırsan kendini geliştiremezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Bilgisayar parçalamak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:İşlemci macunu yenilemeyi ve parça söküp takmayı öğrenirsen hem ekstra takmaya para vermezsin hem de bundan sonra bilgisayarın yavaşladığında veya bozulduğunda kendin tamir edebilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde bilgisayarın bozulduğunda teknik servisi ararsan hem ekstra para ödersin hem de bilgisayarın bozulduğunda tekrar para vermek zorunda kalırsın")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Resmi e posta yazmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin resmi bir e-posta yazmaya çalışıp kendini yazım konusunda geliştirebilir ve başka bir resmi e-posta aldığında kendin yazabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde resmi e-posta yazmak yerine yapay zekaya bana resmi e-posta yaz dersen kendini geliştiremezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Araba kullanmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin araba kullanmayı öğrenip daha sonra kendi başına araba kullanabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde araba kullanmak yerine sürekli taksiye binersen araba kullanmayı öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Ev temizliği yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin ev temizliği yapmayı öğrenip daha sonra kendi başına ev temizliği yapabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde ev temizliği yapmak yerine sürekli temizlikçi çağırırsan ev temizliği yapmayı öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Çamaşır yıkamak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin çamaşır yıkamayı öğrenip daha sonra kendi başına çamaşır yıkayabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde çamaşır yıkamak yerine sürekli çamaşırhaneye başvurursan  çamaşır yıkamayı öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Hediye almak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Karşındakinin zevklerini analiz edip kendi iradenle hediye alabilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde hediye almak yerine sürekli yapay zekaya şu hediyeyi almalı mıyım dersen iraden olmaz")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Not tutmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Dersin önemli yerlerini ayırıp kendi cümlelerinle özetleyuebilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama not tutmak yerine ses kaydı alıp yapay zekadan özetini çıkartırsan yapay zeka sana göre önemli olan yerleri almayabilir ve dersi yanlış öğrenebilirsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Şarkı yazmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kendin şarkı yazabilirsin ve şarkıyı kendin söyleyebilirsin")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Ama her seferinde şarkı yazmak yerine sürekli yapay zekaya şarkı yazdırırsan ve üstüne yapay zekaya şarkıyı söylettirirsen kendini geliştiremezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:3D model yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Blender gibi uygulamalarda kaplamaların mantığını fln öğrenip model üretebilirsin.")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Yapay zekaya 3d model yaptırabilirsin ama model yüksek ihtimalle istediğin gibi olmaz ve hiçbir şey öğrenemezsin")
    input("Devam etmek için Enter'a bas")
    print("Örnek:Minecraft modu yapmak")
    input("Devam etmek için Enter'a bas")
    print("Doğru:Kodları,komutları sıfırdan öğrenip mod yapabilirsin.")
    input("Devam etmek için Enter'a bas")
    print("Yanlış:Yapay zekaya mod yaptırabilirsin ama yaptırdığın mod söylediğinde çok daha farklı olabilir ve hiçbir şey öğrenmemiş olursun.")
    input("Devam etmek için Enter'a bas")

ogrenme_asamasi()